apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: ipv6ulanetworkallocations.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: IPv6ULANetworkAllocation
    plural: ipv6ulanetworkallocations
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
          IPv6ULANetworkAllocation bridges IPAM and Network by creating per-network pools
          and reserving ULA IPv6 CIDRs via VPCIpamPoolCidrAllocation. Exposes allocated
          CIDRs in status for Network to consume.

          ULA (Unique Local Address) uses the fd00::/8 private address space.
          VPCs typically get /48, subnets always get /64 (AWS requirement).
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired state for the ULA IPv6 network allocation.
            required:
            - regionalPoolId
            - scopeId
            - region
            properties:
              managementPolicies:
                type: array
                description: Management operations permitted on composed resources.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              providerConfigRef:
                type: object
                description: Reference to the AWS ProviderConfig.
                properties:
                  name:
                    type: string
                    description: Name of the ProviderConfig. Defaults to "default".
                  kind:
                    type: string
                    description: Kind of the ProviderConfig. Defaults to "ProviderConfig".
                    default: ProviderConfig
              regionalPoolId:
                type: string
                description: |
                  ID of the regional ULA IPAM pool to allocate from (from aws-ipam status).
                  This pool should be the regional pool created by aws-ipam.
              scopeId:
                type: string
                description: |
                  IPAM scope ID (from aws-ipam status.ipam.privateDefaultScopeId).
                  Required for creating child pools.
              region:
                type: string
                description: AWS region where the pool resources are managed.
              locale:
                type: string
                description: |
                  AWS region where CIDRs from these pools can be allocated.
                  When set, only VPCs in this region can use addresses from the pools.
                  Leave unset to inherit from parent pool or let AWS default.
              tags:
                type: object
                description: Additional tags to apply to AWS resources. Merged with default tags.
                additionalProperties:
                  type: string
              vpc:
                type: object
                description: VPC sizing configuration.
                properties:
                  netmaskLength:
                    type: integer
                    description: Netmask length for the VPC ULA CIDR block. Defaults to 48.
                    minimum: 44
                    maximum: 60
                    default: 48
              subnets:
                type: object
                description: Subnet layout configuration.
                properties:
                  availabilityZones:
                    type: array
                    description: Availability zone suffixes (a, b, c). Defaults to [a, b, c].
                    items:
                      type: string
                    default:
                    - a
                    - b
                    - c
                  public:
                    type: object
                    description: Public subnet configuration.
                    properties:
                      enabled:
                        type: boolean
                        description: Whether to create public subnets. Defaults to true.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for public subnets. Must be 64 (AWS requirement).
                        minimum: 64
                        maximum: 64
                        default: 64
                  private:
                    type: object
                    description: Private subnet configuration.
                    properties:
                      enabled:
                        type: boolean
                        description: Whether to create private subnets. Defaults to true.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for private subnets. Must be 64 (AWS requirement).
                        minimum: 64
                        maximum: 64
                        default: 64
          status:
            type: object
            description: Observed state of the ULA IPv6 network allocation.
            properties:
              ready:
                type: boolean
                description: True when all allocations are complete.
              cidr:
                type: string
                description: Allocated VPC CIDR block.
              vpcPoolId:
                type: string
                description: ID of the VPC IPAM pool.
              subnetPoolId:
                type: string
                description: ID of the subnet IPAM pool.
              subnets:
                type: object
                description: Map of subnet name to allocated CIDR.
                x-kubernetes-preserve-unknown-fields: true
